#!/usr/bin/python -B

import argparse
import github
import sys

def set(sha, state, target_url=None, description=None, context=None):
    payload = { "state": state }

    if target_url:
        payload["target_url"] = target_url
    if description:
        payload["description"] = description
    if context:
        payload["context"] = context

    response = github.post(f"statuses/{sha}", payload)

    return github.check(response, [201])

def main():
    parser = argparse.ArgumentParser(description='Process some integers.')
    parser.add_argument("sha")
    parser.add_argument("state", metavar='state', choices=['canceled', 'error', 'failure', 'pending', 'success'])
    parser.add_argument("--url")
    parser.add_argument("--description")
    parser.add_argument("--context")
    args = parser.parse_args()

    return 0 if set(args.sha, args.state, args.url, args.description, args.context) else 1

if __name__ == '__main__':
    sys.exit(main())
