on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit from cicd-code repo to test'
        required: true
        type: string

jobs:
  test-the-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Mark commit as pending
        env:
          PAT: ${{ secrets.PAT }}
        run: ./scripts/status --runid ${{ github.run_id }} ${{ inputs.commit }} pending
