on:
  workflow_dispatch:
    inputs:
      pr:
        description: "PR in code repository to test"
        required: true
        type: string

jobs:
  test-the-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test runner repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Execute test runner
        env:
          PAT: ${{ secrets.PAT }}
        run: ./runner --runid ${{ github.run_id }} ${{ inputs.pr }}
